import { Theme } from '@radix-ui/themes';
import cx from 'clsx';
import type { Metadata } from 'next';
import { Provider } from '@/app/_components/provider';
import localFont from 'next/font/local';
import '@radix-ui/themes/styles.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'SSSSwagger UI',
  description: 'Generated by create next app',
};

const harmonySans = localFont({
  src: [
    {
      path: '../public/fonts/harmonySans/HarmonyOS_Sans_SC_Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/harmonySans/HarmonyOS_Sans_SC_Bold.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/harmonySans/HarmonyOS_Sans_SC_Bold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/harmonySans/HarmonyOS_Sans_SC_Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--harmony-sans',
  display: 'swap',
});

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={cx(harmonySans.variable, 'min-h-screen')}>
        <Provider>
          <Theme
            accentColor='blue'
            className={harmonySans.className}>
            {children}
          </Theme>
        </Provider>
      </body>
    </html>
  );
}
